version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8008"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dummy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: mysqlspring
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummy
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
